version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks: 
      - node-network
    tty: true
    ports:
      - 8080:8080
    entrypoint: dockerize --wait tcp://db:3306 -timeout 60s node app/server.js
    volumes:
      - .:/usr/src/www
      - /usr/src/www/node_modules
    depends_on:
      - db

  db:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./data/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "80:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge